{
 "title": "prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Sidecar Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bolt_sidecar_latest_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\"bolt-(sidecar|mev-boost|boost).*\"})/3600",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Invalid transaction reasons",
   "type": "piechart",
   "description": "Tracks the reasons for rejecting an inclusion request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bolt_sidecar_validation_errors", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Preconfirmed transactions",
   "type": "timeseries",
   "description": "The number of preconfirmed transactions categorized by transaction type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "bolt_sidecar_transactions_preconfirmed",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Gross tip revenue",
   "type": "timeseries",
   "description": "The revenue from all of the preconfirmed transactions. This is \"gross\" revenue because it just adds all of the priority fees in those transactions, which may be partly split with the builder in case of a PBS block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "bolt_sidecar_gross_tip_revenue / 1000000000000000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Inclusion requests accepted",
   "type": "timeseries",
   "description": "The number of inclusion requests that were accepted (i.e. committed to).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "bolt_sidecar_inclusion_commitments_accepted",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Inclusion requests",
   "type": "timeseries",
   "description": "The number of inclusion requests received.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "bolt_sidecar_inclusion_commitments_received",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "PBS blocks proposed",
   "type": "timeseries",
   "description": "The number of PBS blocks proposed (as opposed to local fallback blocks).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "bolt_sidecar_remote_blocks_proposed",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Fallback blocks proposed",
   "type": "timeseries",
   "description": "The number of fallback blocks proposed. Fallback blocks are only proposed in case of a PBS failure. If this number is high, something might be wrong.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "bolt_sidecar_local_blocks_proposed",
     "legendFormat": "blocks"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"bolt-sidecar.*|bolt-mev-boost.*|bolt-boost.*\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"bolt-sidecar.*|bolt-boost.*|bolt-mev-boost.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "description": "Total HTTP requests grouped by HTTP method & response code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "bolt_sidecar_http_requests_total",
     "legendFormat": "{{method}} / {{status}}"
    }
   ]
  },
  {
   "title": "HTTP request durations",
   "type": "histogram",
   "description": "Request processing durations per HTTP method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (bolt_sidecar_http_requests_duration_seconds)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}